### ISSUE TITLE
Docker version of Clipbucket

### ISSUE THREAD

**Issue by JuneZhao** [mtlynch/ansible-role-clipbucket#48]
Hi , just want to check do you have plan to push an working image of CB to dockerhub so that it is more convenient to use?

**Comment by mtlynch** [comment]
Sorry, I'm no longer maintaining this role. I don't think the core developers invest enough into supporting installs. I've switched to [MediaGoblin](https://mediagoblin.org/), which [supports Docker](https://notabug.org/dachary/mediagoblin-docker) out of the box.
